In [1]:
### Requisitos

from pathlib import Path
from datetime import datetime, date, timedelta
from math import floor

import pandas as pd
import pyarrow as pa
import dask as dd

### Pandas

In [2]:
caminho_base = Path("C:/Users/RenatoFileto/curso_bigdata/ModuloPython/data/raw")
caminho_base_csv = caminho_base.joinpath("base_semana02.csv")

In [3]:
### Leitura bases
pandas_df = pd.read_csv(caminho_base_csv, sep=";")
pandas_df

,id,amostra,foto,conceito,var_1,var_2,var_3,var_4,var_5,var_6,...,var_483,var_484,var_485,var_486,var_487,var_488,var_489,var_490,var_491,var_492
0,10000125,OOT,set22,0.0,45,45,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10000177,DES,mai22,0.0,79,79,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000360,OOT,set22,0.0,83,83,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001297,DES,jul22,0.0,81,81,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10002398,DES,dez21,0.0,74,74,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540375,997982,DES,fev22,0.0,181,188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540376,997984,DES,mai22,1.0,190,191,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540377,9987,OOS,dez21,0.0,222,42,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540378,999530,TTD,fev23,NaN,196,200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540379,999914,DES,fev22,0.0,183,188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
### Leitura bases

pandas_it = pd.read_csv(
    caminho_base_csv, 
    sep=";", 
    engine="pyarrow", 
    dtype_backend="pyarrow",
    encoding="latin-1", # "utf8-bom"
    low_memory=True,
    # iterator=True,
    # chunksize=4096
)

# for chunk in pandas_it:
#     print(chunk["var_1"].mean())

In [5]:
pa.null() is None

False

In [9]:
pandas_it["conceito"][:100]

NameError: name 'pandas_arrow_df' is not defined

In [ ]:
100*(pandas_it["conceito"].sum()/pandas_it["id"].count())

0.040937858543987564

In [ ]:
pandas_it["conceito"].count()

411542

In [ ]:
pandas_it[["amostra", "conceito"]].value_counts()/pandas_it["id"].count()

amostra  conceito
DES      0           0.401754
OOS      0           0.172379
OOT      0           0.146508
DES      1           0.023793
OOS      1           0.010200
OOT      1           0.006945
Name: count, dtype: float64

In [ ]:
lista = [pandas_it["var_1"].max(), pandas_it["var_1"].min()]
lista

In [ ]:
pandas_df.iloc[0:, -1]

In [ ]:
pandas_df.loc[1, ["var_1", "var_492"]]

### Execício

Acessem as colunas utilizando diferentes métodos de acesso
- Usando iloc e dois slices diferentes (Ok)
- Usando loc e dois labels diferentes

In [ ]:
pandas_df.iloc[1:10:5, 1:100:2]

pandas_df.iloc[lambda x: x.index % 2 == 0]

In [38]:
pandas_df.loc[:, ["amostra", "conceito"]]

       amostra  conceito
0          OOT       0.0
1          DES       0.0
2          OOT       0.0
3          DES       0.0
4          DES       0.0
...        ...       ...
540375     DES       0.0
540376     DES       1.0
540377     OOS       0.0
540378     TTD       NaN
540379     DES       0.0

[540380 rows x 2 columns]

In [35]:
pandas_df.iloc[:, [1,3]]

       amostra  conceito
0          OOT       0.0
1          DES       0.0
2          OOT       0.0
3          DES       0.0
4          DES       0.0
...        ...       ...
540375     DES       0.0
540376     DES       1.0
540377     OOS       0.0
540378     TTD       NaN
540379     DES       0.0

[540380 rows x 2 columns]

In [39]:
pandas_df.loc[:, ["amostra", "conceito"]] == pandas_df.iloc[:, [1,3]]

        amostra  conceito
0          True      True
1          True      True
2          True      True
3          True      True
4          True      True
...         ...       ...
540375     True      True
540376     True      True
540377     True      True
540378     True     False
540379     True      True

[540380 rows x 2 columns]

In [40]:
pandas_df.iloc[
    [i for i in range(1,3)] + [i for i in range(5,10)], 
    [j for j in range(1,2)] + [j for j in range(20,24)]
]

  amostra  var_17  var_18  var_19  var_20
1     DES     NaN     NaN     NaN     NaN
2     OOT    17.0    17.0    17.0    17.0
5     TTD     NaN     NaN     NaN     NaN
6     OOS     NaN     NaN     NaN     NaN
7     OOS     NaN     NaN     NaN     NaN
8     DES     NaN     3.0     3.0     3.0
9     TTD     NaN     NaN     NaN     NaN

In [41]:
pandas_df.index

RangeIndex(start=0, stop=540380, step=1)

In [43]:
pandas_df

,id,amostra,foto,conceito,var_1,var_2,var_3,var_4,var_5,var_6,...,var_483,var_484,var_485,var_486,var_487,var_488,var_489,var_490,var_491,var_492
0,10000125,OOT,set22,0.0,45,45,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10000177,DES,mai22,0.0,79,79,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10000360,OOT,set22,0.0,83,83,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001297,DES,jul22,0.0,81,81,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10002398,DES,dez21,0.0,74,74,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540375,997982,DES,fev22,0.0,181,188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540376,997984,DES,mai22,1.0,190,191,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540377,9987,OOS,dez21,0.0,222,42,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540378,999530,TTD,fev23,NaN,196,200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540379,999914,DES,fev22,0.0,183,188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
pandas_df= pandas_df.set_index("id")

In [49]:
pandas_df.index
pandas_df.iloc[9987]

amostra       TTD
foto        fev23
conceito      NaN
var_1          43
var_2          43
            ...
var_488       NaN
var_489       NaN
var_490       NaN
var_491       NaN
var_492       NaN
Name: 19556120, Length: 495, dtype: object

In [55]:
# Duas últimas colunas
pandas_df.iloc[:, -2:]

          var_491  var_492
id
10000125      NaN      NaN
10000177      NaN      NaN
10000360      NaN      NaN
10001297      NaN      NaN
10002398      NaN      NaN
...           ...      ...
997982        NaN      NaN
997984        NaN      NaN
9987          NaN      NaN
999530        NaN      NaN
999914        NaN      NaN

[540380 rows x 2 columns]

In [67]:
pandas_df.loc[pandas_df.var_11.notnull()]
# pandas_df.var_11.notnull()

id
10000125    False
10000177    False
10000360    False
10001297    False
10002398    False
            ...
997982      False
997984      False
9987        False
999530      False
999914      False
Name: var_11, Length: 540380, dtype: bool

In [ ]:
pandas_df.loc[pandas_df.var_11.isin([2, 3])]

In [70]:
pandas_df.loc[pandas_df.var_1 > 10]
# pandas_df.var_1 > 10
# pandas_df.loc[: , 99*[True, False, True, False, False]]

,amostra,foto,conceito,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_483,var_484,var_485,var_486,var_487,var_488,var_489,var_490,var_491,var_492
id,,,,,,,,,,,,,,,,,,,,,
10000125,OOT,set22,0.0,45,45,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000177,DES,mai22,0.0,79,79,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000360,OOT,set22,0.0,83,83,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10001297,DES,jul22,0.0,81,81,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10002398,DES,dez21,0.0,74,74,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997982,DES,fev22,0.0,181,188,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997984,DES,mai22,1.0,190,191,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987,OOS,dez21,0.0,222,42,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999530,TTD,fev23,NaN,196,200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999914,DES,fev22,0.0,183,188,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Pergunta

Utilizando a semântica de acesso '.' o que ocorre se a coluna possuir caracteres especiais?

In [72]:
pandas_df_2 = pandas_df

pandas_df_2["amostra"] = ""
pandas_df_2

,amostra,foto,conceito,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_483,var_484,var_485,var_486,var_487,var_488,var_489,var_490,var_491,var_492
id,,,,,,,,,,,,,,,,,,,,,
10000125,,set22,0.0,45,45,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000177,,mai22,0.0,79,79,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000360,,set22,0.0,83,83,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10001297,,jul22,0.0,81,81,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10002398,,dez21,0.0,74,74,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997982,,fev22,0.0,181,188,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997984,,mai22,1.0,190,191,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987,,dez21,0.0,222,42,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999530,,fev23,NaN,196,200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999914,,fev22,0.0,183,188,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pandas_df["var_1"].mean()

pandas_df["var_1_diff_avg"] = pandas_df["var_1"] - pandas_df["var_1"].mean()

# pandas_df.var_1.map(lambda r: r - valor_media_var_1)

def media_pontos(row):
    valor_media_var_1 = pandas_df["var_1"].mean()
    row.var_1 = row.var_1 - valor_media_var_1
    return row


pandas_df.apply(media_pontos, axis="columns")

### Exercício

1. Calcular coeficiente de inclinação da reta que passa pelos valores da variável 1 nos últimos seis meses;
2. Escrever uma função (anônima ou não), que faça a diferença entre a média e a mediana.

### Dask