### Pandas

In [53]:
### Requisitos
import sys
import io
from decimal import Decimal
from math import pi

import pandas as pd
import numpy as np
import pyarrow as pa

pd.set_option("mode.copy_on_write", True)
pd.options.mode.copy_on_write = "warn"

#### Criação, Leitura e escrita de dados

##### Estruturas de Dados

1. **Series:** Unidimensional, é uma espécie de lista nomeada homogênea cujos valores podem ser de qualquer tipo. 
2. **Dataframes:** Bidimensional, pode ser pensado como um array de duas dimensões ou como uma tabela com linhas e colunas. As colunas de um dataframe são séries.

##### Criação

Dataframes podem ser criados a partir de um dicionário, onde cada Chave definirá o nome da coluna e o o valor representará as entradas do DataFrame. O método construtor da classe DataFrame aceita outros tipos de parâmetros como por exemplo iteradores, como listas e ndarray (numpy) desde que sejam estruturados ou homogêneos. 

 A partir da versão 2.0 o Pandas suporta nativamente os tipos do Arrow e em determinados casos, escolher entre os backends de tipos Arrow e Numpy faz muita diferença para um *Workflow* de dados. Veja mais em [PyArrow e Pandas](https://pandas.pydata.org/docs/user_guide/pyarrow.html)

In [54]:
df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
        "G": pd.Series(Decimal(pi**2), index=list(range(4)), dtype="float"),
    }

)

df

     A          B    C  D      E    F         G
0  1.0 2013-01-02  1.0  3   test  foo  9.869604
1  1.0 2013-01-02  1.0  3  train  foo  9.869604
2  1.0 2013-01-02  1.0  3   test  foo  9.869604
3  1.0 2013-01-02  1.0  3  train  foo  9.869604

In [78]:
df.dtypes
df.memory_usage()

Index     32
A         32
B         32
C         16
D         16
E        128
F         32
G         32
dtype: int64

In [82]:
decimal_type = pd.ArrowDtype(pa.decimal128(3, scale=2))

df_arrow = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype=pd.ArrowDtype(pa.float16())),
        "D": pd.array([3] * 4, dtype=pd.ArrowDtype(pa.uint16())),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": pa.array(["foo"]*4, type=pa.string()),
        "G": pd.Series((pi**2), index=list(range(4)), dtype=decimal_type),
    }

)

df

     A          B    C  D      E    F         G
0  1.0 2013-01-02  1.0  3   test  foo  9.869604
1  1.0 2013-01-02  1.0  3  train  foo  9.869604
2  1.0 2013-01-02  1.0  3   test  foo  9.869604
3  1.0 2013-01-02  1.0  3  train  foo  9.869604

In [83]:
#df_arrow.dtypes
df_arrow.memory_usage()

Index     32
A         32
B         32
C          9
D          8
E        128
F         32
G         65
dtype: int64

#### Leitura

1. Arquivos CSV


**Parâmetros**
- encoding
- engine 
- header
- sep
- low_memory
- dtype_backend
- chunksize
- iterator

Ao realizar a leitura de arquivos pode ser informada a engine que fará a leitura e avaliação dos dados

In [86]:
data = io.StringIO("""a,b,c
   1,2.5,True
   3,4.5,False
""")

df_csv = pd.read_csv(data, engine="pyarrow")
df_csv.dtypes

a      int64
b    float64
c       bool
dtype: object

In [85]:
data = io.StringIO("""a,b,c
   1,2.5,True
   3,4.5,False
""")

df_arrow_csv = pd.read_csv(data, dtype_backend="pyarrow", engine="pyarrow")
df_arrow_csv.dtypes

a     int64[pyarrow]
b    double[pyarrow]
c      bool[pyarrow]
dtype: object


2. Arquivos Parquet

#### Tipos de Dados e Valores Nulos

#### Indexes e seleção

#### Sumários e agregações

#### Agrupamentos e ordenação

#### Combinando DataFrames 

##### Combinações Verticais

##### Combinações Horizontais

#### Pipes e o método Assign

### Dask

### Referências

1. **Pandas Workout** - Reuven M. Lerner, Manning Publications
2. **Python Data Analytics** - Fabio Nelli, Apress
3. **Modern Pandas Tutorial** - [Tom's Blog](https://tomaugspurger.net/posts/modern-1-intro/)
4. **Practical Pandas** - [Tom's Blog](https://tomaugspurger.net/posts/pp01/)